# Generated by Django 5.0.6 on 2024-06-06 14:48

import ai_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000000)),
                ('answer', models.CharField(max_length=1000000)),
                ('chat_type', models.CharField(choices=[('s', 'system'), ('n', 'normal'), ('c', 'controll')], default='n', max_length=30)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_chats', to='ai_api.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Files_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[ai_api.models.validate_file_extension])),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='its_files', to='ai_api.conversation')),
            ],
        ),
    ]
