# Generated by Django 5.0.6 on 2024-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api', '0002_alter_files_data_file_alter_files_data_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('s', 'system'), ('n', 'normal'), ('c', 'controll'), ('r', 'rag')], default='n', max_length=30),
        ),
    ]
